"""Migracion inicial

Revision ID: 1dab8596851b
Revises: 
Create Date: 2021-05-18 13:53:44.575736

"""
from alembic import op
import sqlalchemy as sa
from config.db import GUID

# revision identifiers, used by Alembic.
revision = '1dab8596851b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('nombre_completo', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personaje')
    # ### end Alembic commands ###
